language: java
sudo: false # faster builds
jdk:
  - oraclejdk8

# Use updated jdk version instead of buggy default
addons:
  apt:
    packages:
      - oracle-java8-installer

after_success:
  - bash <(curl -s https://codecov.io/bash)